/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConnectionDb;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import observateurs.Observateurs;
import observateurs.Observe;

/**
 *
 * @author Padovano
 */
public class initStyle extends javax.swing.JInternalFrame implements Observe,Observateurs{

    private final ConnectionDb conn=ConnectionDb.instance();
    private Fab_list dialog;
    private Map<String,Integer> type;
    private boolean est_vide=false;
    private DefaultTableModel tbm;
    private int proto_id;
    
    /**
     * Creates new form initSize
     */
    public initStyle() {
        initComponents();
        tbm = (DefaultTableModel)grid_style.getModel();
        init();
        dialog=new Fab_list(new javax.swing.JFrame(), true);
        dialog.ajouterObservateur(this);
        this.ajouterObservateur(dialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        delete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_style = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_pattern = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_proto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_profam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DESC = new javax.swing.JTextField();
        CUST = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        type_list = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid_style = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        wash_step = new javax.swing.JCheckBox();
        match_book_step = new javax.swing.JCheckBox();
        press_step = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        delete.setText("remove");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        popup.add(delete);

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Infos Style"));

        jLabel1.setText("Style:");

        txt_style.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_styleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_styleFocusLost(evt);
            }
        });

        jLabel2.setText("Pattern:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("(Familly)");

        jLabel4.setText("Proto:");

        jLabel5.setText("Proto familly:");

        jLabel17.setText("Description");

        jLabel19.setText("Customer");

        CUST.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selected--", "HWY", "AUG", "CHS", "FSM", "EDG", "GBG" }));

        jLabel6.setText("Fabric Type:");

        grid_style.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FAB ID", "FABRIC", "TYPE ID", "TYPE", "is_new"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid_style.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid_styleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grid_style);
        if (grid_style.getColumnModel().getColumnCount() > 0) {
            grid_style.getColumnModel().getColumn(0).setMinWidth(0);
            grid_style.getColumnModel().getColumn(0).setMaxWidth(0);
            grid_style.getColumnModel().getColumn(2).setMinWidth(0);
            grid_style.getColumnModel().getColumn(2).setMaxWidth(0);
            grid_style.getColumnModel().getColumn(4).setMinWidth(0);
            grid_style.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jButton1.setText("ADD FABRIC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "post sewing step", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        wash_step.setText("WASHING");

        match_book_step.setText("MATCHBOOK");

        press_step.setText("PRESS");

        jButton3.setText("SAVE STEPS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wash_step)
                .addGap(106, 106, 106)
                .addComponent(match_book_step)
                .addGap(119, 119, 119)
                .addComponent(press_step)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wash_step)
                    .addComponent(match_book_step)
                    .addComponent(press_step))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton2.setText("SAVE STYLE FABRIC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_style, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_pattern, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(txt_profam, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DESC)
                    .addComponent(CUST, 0, 145, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_proto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_list, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DESC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_proto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_profam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CUST, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(type_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_styleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_styleFocusLost
        // TODO add your handling code here:
        est_vide=true;
        Object[] data=exist(txt_style.getText().trim());
        if(data!=null){
            est_vide=false;
            txt_proto.setText(data[1].toString());
            txt_pattern.setText(data[3].toString());
            txt_profam.setText(data[4].toString());
            DESC.setText(data[5].toString());
            System.out.println("customer:"+data[6]);
            CUST.setSelectedItem(data[6].toString().trim());
            load((Integer)data[0]);
            
        }
        
//        if(!est_vide){
//            System.out.println("not empty");
//            update_btn.setEnabled(true);
//            jButton1.setEnabled(false);
//        }else
//        {
//            System.out.println("empty");
//            update_btn.setEnabled(false);
//            jButton1.setEnabled(true);
//        }
    }//GEN-LAST:event_txt_styleFocusLost

    private void txt_styleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_styleFocusGained
        // TODO add your handling code here:
        txt_proto.setText(null);
        txt_pattern.setText(null);
        txt_profam.setText(null);
        DESC.setText(null);
        grid_style.setGridColor(Color.blue);
        tbm.setRowCount(0);
        CUST.setSelectedIndex(0);
        proto_id=0;
        //jButton1.setEnabled(false);
    }//GEN-LAST:event_txt_styleFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        alerter("new_style");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void grid_styleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid_styleMouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==3){
            if(!grid_style.getSelectionModel().isSelectionEmpty()){
             
        popup.show(grid_style, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_grid_styleMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        if(tbm.getValueAt(grid_style.getSelectedRow(), 4).equals("old")){
            
            grid_style.setValueAt("remove",grid_style.getSelectedRow(), 4);
        
        }else if(tbm.getValueAt(grid_style.getSelectedRow(), 4).equals("new"))
            tbm.removeRow(grid_style.getSelectedRow());
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String log="";
        String requete="insert into proto_style (style,proto,brand,styfam,profam,description) values("
                + "?,?,?,?,?,?)";
        if(grid_style.getRowCount()>0){
            
        if(!est_vide)
            requete="update proto_style set style=?,proto=?,brand=?,styfam=?,profam=?,description=? where proto_id="+proto_id;
        if(conn.Update(requete, 1, txt_style.getText().trim(),txt_proto.getText().trim(),CUST.getSelectedItem().toString(),
                txt_pattern.getText().trim(),txt_profam.getText().trim(),DESC.getText().trim())){
            if(est_vide)
                proto_id=conn.getLast();
            requete="insert into fab_style(proto_id,fab_id,type_id,proto_opt) values (?,?,?,1)";
            for(int i=0;i<grid_style.getRowCount();i++){
                String action_mad=grid_style.getValueAt(i, 4).toString();
                if(!action_mad.equals("old")){
                int fab_id=(Integer)grid_style.getValueAt(i, 0);
                int type_id=(Integer)grid_style.getValueAt(i, 2);
                
                if(action_mad.equals("remove"))
                    requete="delete from fab_style where proto_id=? and fab_id=? and type_id=?";
                if(!conn.Update(requete, 0, proto_id,fab_id,type_id)){
                    log+=conn.getErreur()+"\n";
                }
                }
            }
            if(log.isEmpty()){
                log="success";
                txt_proto.setText(null);
        txt_pattern.setText(null);
        txt_profam.setText(null);
        DESC.setText(null);
        grid_style.setGridColor(Color.blue);
        tbm.setRowCount(0);
        CUST.setSelectedIndex(0);
        proto_id=0;
            }
            
        }else
            log+=conn.getErreur()+"\n";
        
        }
        JOptionPane.showMessageDialog(this, log);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String log="";
        if(proto_id==0){
            log="please make sure you have indaicate the style and the style is already exist";
        }else{
            String requete="insert into operations_styles values(?,"+proto_id+")";
            if(wash_step.isSelected()){
                if(!conn.Update(requete, 0, 1))
                    log+=conn.getErreur()+"\n";
            }
            if(match_book_step.isSelected()){
                if(!conn.Update(requete, 0, 2))
                    log+=conn.getErreur()+"\n";
            }
            if(press_step.isSelected()){
                if(conn.Update(requete, 0, 3))
                    log+=conn.getErreur()+"\n";
            }
                        
           if(log.isEmpty()){
               log="success";
               press_step.setSelected(false);
               match_book_step.setSelected(false);
               wash_step.setSelected(false);
           }
        }
        JOptionPane.showMessageDialog(this, log);
    }//GEN-LAST:event_jButton3ActionPerformed

     private void save(){
        String requete="insert into proto_style (style,proto,brand,styfam,profam,description) values("
                + "?,?,?,?,?,?)";
        if(!est_vide)
            requete="update proto_style (style,proto,brand,styfam,profam,description) values("
                + "?,?,?,?,?,?)";
        if(conn.Update(requete, 1, txt_style.getText().trim(),txt_proto.getText().trim(),CUST.getSelectedItem().toString(),
                txt_pattern.getText().trim(),txt_profam.getText().trim(),DESC.getText().trim())){
            int style_id=conn.getLast();
            requete="insert into fab_style(proto_id,fab_id,type_id,proto_opt) values (?,?,?,1)";
        }
     }
    private Object[] exist(String style){
        Object[] data=null;
        String requete="select * from proto_style where style=?";
        ResultSet rs=conn.select(requete, style);
        try {
            
            while(rs.next()){
                data=new Object[7];
                data[0]=rs.getInt("proto_id");
                data[1]=rs.getString("style");
                data[2]=rs.getString("proto");
                data[3]=rs.getString("styfam");
                data[4]=rs.getString("profam");
                data[5]=rs.getString("description");
                data[6]=rs.getString("brand");
                proto_id=rs.getInt("proto_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(initStyle.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        return data;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CUST;
    private javax.swing.JTextField DESC;
    private javax.swing.JMenuItem delete;
    private javax.swing.JTable grid_style;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox match_book_step;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JCheckBox press_step;
    private javax.swing.JTextField txt_pattern;
    private javax.swing.JTextField txt_profam;
    private javax.swing.JTextField txt_proto;
    private javax.swing.JTextField txt_style;
    private javax.swing.JComboBox type_list;
    private javax.swing.JCheckBox wash_step;
    // End of variables declaration//GEN-END:variables

    private void load(int proto){
        String requete="select * from stylemaster where proto_id=?";
        ResultSet rs=conn.select(requete, proto);
        Object[] data=null;
        tbm.setNumRows(0);
        try {
            while(rs.next()){
                tbm.addRow(new Object[]{rs.getInt("FAB_ID"),rs.getString("FABNM"),rs.getInt("TYPE_ID"),rs.getString("TYPE"),"old"});
            }
        } catch (SQLException ex) {
            Logger.getLogger(NEW_Style.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void ajouterObservateur(Observateurs ob) {
        this.obs.add(ob);
    }

    @Override
    public void retirerObservateur(Observateurs ob) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void alerter(Object... ob) {
        obs.stream().forEach((o) -> {
            o.executer(ob);
        });
    }

    @Override
    public void executer(Object... obs) {
        if(obs[0].equals("fill_tab")){
            tbm.addRow(new Object[]{obs[2],obs[1],type.get(type_list.getSelectedItem().toString()),type_list.getSelectedItem().toString(),"new"});
        }
    }
    
    private void init(){
        String requete="select * from type";
        ResultSet rs=conn.select(requete);
        Object[] data=null;
        txt_proto.setText(null);
        txt_pattern.setText(null);
        txt_profam.setText(null);
        tbm.setNumRows(0);
        type=new HashMap<>();
        type_list.addItem("-- Select Fabric Type --");
        type_list.setSelectedIndex(0);
        try {
            while(rs.next()){
                type.put(rs.getString("TYPE"),rs.getInt("TYPE_ID"));
                type_list.addItem(rs.getString("TYPE"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NEW_Style.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
