/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import connection.ConnectionDb;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import observateurs.Observateurs;

/**
 *
 * @author Duvers
 */
public class Sewing_prod_before_eight extends javax.swing.JInternalFrame implements Observateurs {
    private final ConnectionDb conn = ConnectionDb.instance();
    private DefaultTableModel tbm;
    private Set<Object[]> datalist;
    private Date dat;
    DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
    /**
     * Creates new form Sewing_prod
     */
    public Sewing_prod_before_eight() {
        
        initComponents();
        tbm = (DefaultTableModel) grid_sew.getModel();
        mostrar();
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid_sew = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Sewing Production");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        grid_sew.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PO NUM", "STYLE", "COLOR CODE", "COLOR", "SIZE", "QTY", "TICKET", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grid_sew);
        if (grid_sew.getColumnModel().getColumnCount() > 0) {
            grid_sew.getColumnModel().getColumn(3).setMinWidth(0);
            grid_sew.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jTextField1.setFocusCycleRoot(true);

        jLabel1.setText("Sewing Traveler");

        timer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timer.setText("jLabel2");

        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            System.out.println(evt.getKeyCode()==10);
            if(jTextField1.getText().trim().isEmpty()){
                return;
            }
                get(jTextField1.getText().trim());
                //mostrar();
                load();
                jTextField1.setText("");
        }
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTable grid_sew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables

private void get(String sew){
    
    //tbm.setRowCount(0);
    //Pattern p=Pattern.compile("[");
    String requete="select * from sewing_production where Slot=?";
    System.out.println(requete);
    ResultSet rs=conn.select(requete, sew);
    boolean exist=false,used=false, valid=true;
    String sewing_t="",item="",type="",lot="";
    Date dat1=new Date();
    int bar=29;
    int id=0;
    int qty=0,QTY_CUT=0;
    Object[] data=new Object[8];
        try {
            while(rs.next()){
                exist=true;
                type=rs.getString("type_sew");
                id=rs.getInt("sew_id");
                if(rs.getInt("status")==1)
                    used=true;
                if(rs.getInt("status")==2)
                    valid=false;
                qty=rs.getInt("QTY_PER_LOT");
                
                sewing_t=rs.getString("S_TRAVELLER").trim();
                item=rs.getString("slot");
                lot=rs.getString("lot_stickers");
                //dat=rs.getDate("modified");
            }   } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(exist){
            if(!used){
                if(valid){
                if(qty==0){
                    if(type.equals("first")){
                        
                    if(lastInsertBlank(lot)!=null){
                        Date mod=lastInsertBlank(lot);
                        String date_mod=1900+mod.getYear()+"-";
                        date_mod+=mod.getMonth()+"-";
                        date_mod+=mod.getDate();
                        
                        String dat_new=1900+dat1.getYear()+"-";
                        dat_new+=dat1.getMonth()+"-";
                        dat_new+=dat1.getDate();
                        if(date_mod.equals(dat_new)){
                            
                            JOptionPane.showMessageDialog(this, "you cannot scan multiple blank stickers in a same date");
                            return;
                        }
                    }
                        }
                        bar=balance(lot,item);
                        System.out.println("balance:"+bar);
                        if(bar>30)
                            bar=25;
                    String option="";
                    do{
                    option=JOptionPane.showInputDialog(this, "please Confirm quantity"
                            + "\n Quantity must inferior or equals to:"+bar, "Confirmation", JOptionPane.WARNING_MESSAGE);
                    }while(option.trim().isEmpty() || Pattern.matches("\\d+",option)==false||Integer.parseInt(option)>bar);
                    System.out.println(option);
                    
                    qty=Integer.parseInt(option);
                    if(type.equals("first")){
                        if(sumBlank(lot)+qty>sumInvalid(lot))
                        setInvalid(first(lot));
                    }
                    setqty(Integer.parseInt(option),sew);
                    
                    
                    }else if(id==last(lot)){
                    System.out.println("okkkk");
                    //setInvalidBlank(sewing_t);
                }
                    System.out.println("last:"+last(lot));
                setSewn(sew);
                
                
                String []posku=sewing_t.replace(".", "-").split("-");
                String color,Code;
               color=null;
               Code=posku[2];
                data[0]=posku[0];
                   data[1]=posku[1];
                   data[6]=item;
                   data[7]=type;
                   data[2]=Code;
                   data[3]=color;
                   data[4]=posku[3];
                   data[5]=qty;
                   datalist.add(data);
                
                
                String req="select qty from sew_start where stickers=?";
                ResultSet r=conn.select(req, lot);
                    try {
                        while(r.next()){
                            QTY_CUT=r.getInt("qty");
                        }   } catch (SQLException ex) {
                        Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
                    }
                String requete1="insert into TRANSAC(TRANSACT,ITEM,QTY,ACT_TYPE,ACT_NAME,SUB_ITEM,QTY_SUBITEM,user_id) values ('sewing',?,?,3,?,?,?,?)";
                    conn.Update(requete1, 0, new Object[]{sewing_t,QTY_CUT,"sewing",item,qty,Principal.user_id});
                }else{
                    JOptionPane.showMessageDialog(this, "This sticker you scan is invalid", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "This sticker you scan is already scanned", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "This sticker you scan is not valid", "Alert", JOptionPane.ERROR_MESSAGE);
        }
        
}
    private void mostrar(){
    
    tbm.setRowCount(0);
    datalist=new LinkedHashSet<>();
    String requete="select * from sewing_production where Status=1";
    System.out.println(requete);
    ResultSet rs=conn.select(requete);
        try {
            while(rs.next()){
                String []posku=rs.getString("S_TRAVELLER").trim().replace(".", "-").split("-");
                   
                String color,Code;
               color=null;
               Code=posku[2];
               
             
                   Object[] data=new Object[8];
                   data[0]=posku[0];
                   data[1]=posku[1];
                   data[6]=rs.getString("slot");
                   data[7]=rs.getString("type_sew");
                   data[2]=Code;
                   data[3]=color;
                   data[4]=posku[3];
                   data[5]=rs.getString("QTY_PER_LOT");
                   datalist.add(data);
                   tbm.addRow(data);
            }   } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void load(){
        tbm.setRowCount(0);
        datalist.stream().forEach((data) -> {
            tbm.addRow(data);
        });
    }
    
    private boolean setqty(int qty,String sew){
        String requete="update sewing_production set QTY_PER_LOT=? where slot=?";
        return conn.Update(requete, 0, new Object[]{qty,sew});
    }
    
    private void setInvalidBlank(String travel){
        String requete="select sew_id from sewing_production where S_TRAVELLER=? and QTY_PER_LOT=0 and type_sew='first'";
        ResultSet rs=conn.select(requete,travel);
        try {
            while(rs.next())
            setInvalid(rs.getInt("sew_id"));
        } catch(SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int last(String trave){
        String requete="select max(sew_id) SEW_ID from sewing_production where lot_stickers=? and STATUS=0 and QTY_PER_LOT<>0";
        ResultSet rs=conn.select(requete,trave);
        int id=0;
        try {
            while(rs.next()){
                id=rs.getInt("sew_id");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    private int first(String trave){
        String requete="select min(sew_id) SEW_ID from sewing_production where lot_stickers=? and STATUS=0 and QTY_PER_LOT<>0";
        ResultSet rs=conn.select(requete,trave);
        int id=0;
        try {
            while(rs.next()){
                id=rs.getInt("sew_id");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    private boolean setSewn(String sew){
        String requete="update sewing_production set status=1, modified=? where slot=?";
        return conn.Update(requete, 0, new Object[]{dat,sew});
    }
    private boolean setInvalid(int id){
        String requete="update sewing_production set status=2,modified=? where sew_id=?";
        return conn.Update(requete, 0, dat,id);
    }
    private Date lastInsertBlank(String s_traveller){
        String requete="select max(modified) modified from sewing_production where lot_stickers=? and STATUS=2";
        ResultSet rs=conn.select(requete,s_traveller);
        Date dat1=null;
        try {
            while(rs.next()){
                dat1=rs.getDate("modified");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dat1;
    }
    private int lastVal(String trave){
        String requete="select qty from production_scan where slot=?";
        ResultSet rs=conn.select(requete,trave);
        int id=0;
        try {
            while(rs.next()){
                id=rs.getInt("qty");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    private int entry(String travel){
        String requete="select sum(QTY_PER_LOT) qty from sewing_production where lot_stickers=? and status=1 ";
        ResultSet rs=conn.select(requete,travel);
        int id=0;
        try {
            while(rs.next()){
                id=rs.getInt("qty");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    private int balance(String trave,String slot){
        return lastVal(slot)-entry(trave);
    }
    
    private int sumInvalid(String sew){
        String requete="select sum(QTY_PER_LOT) invalid from sewing_production where lot_stickers=? and STATUS=2";
        ResultSet rs=conn.select(requete,sew);
        int nb=0;
        try {
            while(rs.next()){
                nb=rs.getInt("invalid");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nb;
    }
    
    private int sumBlank(String sew){
        String requete="select sum(QTY_PER_LOT) blank from sewing_production where lot_stickers=? and STATUS=1 and sew_id >? and"
                + " type_sew='first'";
        ResultSet rs=conn.select(requete,sew,last(sew));
        int nb=0;
        try {
            while(rs.next()){
                nb=rs.getInt("blank");
                 }   
        } catch (SQLException ex) {
            Logger.getLogger(Sewing_prod.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nb;
    }

    @Override
    public void executer(Object... obs) {
        System.out.println("obs");
        if(obs[0].equals("modifier date"))
        {
            dat=(Date)obs[1];
          date.setText(dateFormat.format(dat));
          timer.setText(timeFormat.format(dat));
        }
    }
    
    
}