/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Padovano
 */
public class Waiting extends javax.swing.JPanel {

    private Image im;
    private int x,y;
    /**
     * Creates new form Waiting
     */
    public Waiting() {
        initComponents();
        
        //init();
    }

    public void setX(int x) {
        this.x = x;
    }

    public void setY(int y) {
        this.y = y;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void paintComponent(Graphics g){
        try {
            im=ImageIO.read(new File("src/pict/load.png"));
        } catch (IOException ex) {
            Logger.getLogger(Waiting.class.getName()).log(Level.SEVERE, null, ex);
        }
        Graphics2D gd=(Graphics2D)g;
        BufferedImage img=new BufferedImage(im.getWidth(null),im.getHeight(null),BufferedImage.TYPE_INT_ARGB);
        gd.setColor(Color.red);
        gd.drawRect(0, 0, this.getWidth(), this.getHeight());
        int posx=img.getWidth();
        int posy=img.getHeight();
        gd.drawImage(im,(this.getWidth()-posx)/2 , (this.getWidth()-posx)/2,null);
        gd.drawString("Loading...",(this.getWidth()-posx)/2, (this.getWidth()-posx)/2);
        AffineTransform at=new AffineTransform();
        at.scale(2.0, 2.0);
        at.rotate(x, posx/2, posy/2);
        //gd.dra
        gd.drawImage(im, at, null);
        //gd.drawIm
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
