/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.report;

import codebar.Barcode;
import codebar.BarcodeFactory;
import codebar.BarcodeType;
import connection.ConnectionDb;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import observateurs.Observateurs;
import observateurs.Observe;
import view.Confirm_Receiver;

/**
 *
 * @author Padovano
 */
public class sewing extends javax.swing.JInternalFrame implements Observe{
private final ConnectionDb conn = ConnectionDb.instance();
private DefaultTableModel tbm;
    /**
     * Creates new form Confirm_at_soabar
     */
    public sewing() {
        initComponents();
        init();
        observa=new Confirm_Receiver(null,false);
    this.ajouterObservateur(observa);
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GRID_DATA = new javax.swing.JTable();

        setClosable(true);
        setTitle("At Embelisment");

        jLabel1.setText("SCAN SEWING:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(22, 22, 22))))
        );

        GRID_DATA.setAutoCreateRowSorter(true);
        GRID_DATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SEWING TRAVELLER", "PO", "STYLE", "COLOR CODE", "COLOR", "SIZE", "QTY", "SEWING CARD", "sewing_no", "Accum. Qty", "customer", "order", "plan", "proto_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GRID_DATA);
        if (GRID_DATA.getColumnModel().getColumnCount() > 0) {
            GRID_DATA.getColumnModel().getColumn(10).setMinWidth(0);
            GRID_DATA.getColumnModel().getColumn(10).setMaxWidth(0);
            GRID_DATA.getColumnModel().getColumn(11).setMinWidth(0);
            GRID_DATA.getColumnModel().getColumn(11).setMaxWidth(0);
            GRID_DATA.getColumnModel().getColumn(12).setMinWidth(0);
            GRID_DATA.getColumnModel().getColumn(12).setMaxWidth(0);
            GRID_DATA.getColumnModel().getColumn(13).setMinWidth(0);
            GRID_DATA.getColumnModel().getColumn(13).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            System.out.println(evt.getKeyCode()==10);
            //if(!jTextField1.getText().trim().isEmpty())
                get(jTextField1.getText().trim());
                mostrarData();
                jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void get(String sew){
    String state=state(sew);
    boolean check=false;
    if(!state.isEmpty()){
    if(state.equals("5")){
        JOptionPane.showMessageDialog(this, "this po sku is closed");
    }else{
        Object[] data=new Object[8];
        
        
        for(int i=0;i<GRID_DATA.getRowCount();i++){
            if(GRID_DATA.getValueAt(i, 7).toString().trim().equals(sew)){
                check=true;
                data[0]=GRID_DATA.getValueAt(i, 0);
                data[1]=GRID_DATA.getValueAt(i, 1);
                data[2]=GRID_DATA.getValueAt(i, 2);
                data[3]=GRID_DATA.getValueAt(i, 3);
                data[4]=GRID_DATA.getValueAt(i, 4);
                data[5]=GRID_DATA.getValueAt(i, 5);
                data[6]=GRID_DATA.getValueAt(i, 6);
                data[7]=GRID_DATA.getValueAt(i, 7);
                 print(data[4].toString().trim(),data[3].toString().trim(),data[5].toString().trim(),
                         Integer.parseInt(data[6].toString()),data[7].toString().trim(),data[1].toString().trim(),data[2].toString().trim(),GRID_DATA.getValueAt(i, 8).toString()
                         ,Integer.parseInt(GRID_DATA.getValueAt(i, 9).toString()),GRID_DATA.getValueAt(i, 10).toString(),Integer.parseInt(GRID_DATA.getValueAt(i, 11).toString()),
                         Integer.parseInt(GRID_DATA.getValueAt(i, 12).toString()),Integer.parseInt(GRID_DATA.getValueAt(i, 13).toString()));
            }
        }
        if(check){
        alerter("Transfer to sew2",data);
        ((JDialog)observa).setModal(true);
        ((JDialog)observa).setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "this sticker is not valid!\n"
                    + "We cannot deliver anything\n"
                    + "\t- this lot has never been delivered in pad print.\n"
                    + "\t\t or\n "
                    + "\t- we have nothing to deliver for this lot.");
    }
    }else
        JOptionPane.showMessageDialog(this, "this sticker is not valid!\n");
}
    private void init(){
        GRID_DATA.getTableHeader().setFont( new Font( "Arial" , Font.BOLD, 13 ));
        tbm = (DefaultTableModel) GRID_DATA.getModel();
       mostrarData();
    }
    
    private String state(String sewing){
        String query = "SELECT * from shoporder where ordnum_147=?";
        ResultSet rs = conn.select(query,sewing);
        try {
        while (rs.next()){
            return rs.getString("status_147");
        }
    } catch (SQLException ex) {
        Logger.getLogger(sewing.class.getName()).log(Level.SEVERE, null, ex);
    }
        return "";
    }
    private Map<String ,Integer[]> at_sewing(){
        String requete="Select po,sku, qty,nb  from At_sewing1";
        Map<String,Integer[]> sew=new HashMap<>();
        ResultSet rs=conn.select(requete);
        try {
            while(rs.next()){
                String order=rs.getString("po").trim();
                order+="."+rs.getString("sku").trim();
                sew.put(order, new Integer[]{rs.getInt("qty"),rs.getInt("nb")});
                       
            }
        } catch (SQLException ex) {
               //Logger.getLogger(Cansew.class.getName()).log(Level.SEVERE, null, ex);
           }
        return sew;
    }
    private void mostrarData(){
        tbm.setRowCount(0);
        Map<String ,Integer[]> atSew=at_sewing();
         String query = "SELECT * from at_padprint";
            ResultSet rs = conn.select(query);
               
    try {
        while (rs.next()){
            String color,Code;
            
               Code=rs.getString("color_code").trim();
               color=Code+"-"+rs.getString("color").trim();
               String order=rs.getString("po").trim();
                order+="."+rs.getString("sku").trim();
               int data1=0;
               int nb=1;
               try{
                   data1=atSew.get(order)[0];
                  
               }catch(NullPointerException e){
                   data1=0;
               }
               try{
                    nb+=atSew.get(order)[1];
               }catch(NullPointerException e){
                   nb=1;
               }
               if(rs.getInt("qty")-data1>0){
                   Object[] data=new Object[14];
                   data[0]=rs.getString("sewing_traveller");
                   data[1]=rs.getString("po");
                   data[2]=rs.getString("style");
                   data[3]=Code;
                   data[4]=color;
                   data[5]=rs.getString("size");
                   data[6]=rs.getInt("qty")-data1;
                   data[7]=rs.getString("order_num");
                   data[8]=nb;
                   data[9]=rs.getInt("qty");
                   data[10]=rs.getString("brand");
                   data[11]=rs.getInt("pieces");
                   data[12]=rs.getInt("planned");
                   data[13]=rs.getInt("proto_id");
                   tbm.addRow(data);
               }
        }
    } catch (SQLException ex) {
        Logger.getLogger(sewing.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GRID_DATA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private Observateurs observa;
    @Override
    public void ajouterObservateur(Observateurs ob) {
        obs.add(ob);
    }

    @Override
    public void retirerObservateur(Observateurs ob) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void alerter(Object... ob) {
        for(Observateurs o:obs)
            o.executer(ob);
    }
    
    private void print(String color,String color_code,String size,int qty,String code,String pot,String stylet,String no,int cum,String client,int order,int plan,int proto_id){
        ArrayList<Data> listdata=new ArrayList<>();
                  
        
        
        Data d=new Data();
                  d.setSize(size);
                  d.setCode(code);
                  d.setQty(qty);
                  listdata.add(d);
                  Barcode b=BarcodeFactory.createBarcode(BarcodeType.Code128,code);
        b.export("jpg", 1, 50 ,true, "src/report/barcode/"+code+".jpg");
        //}
        try{ 
            File source = new File("src/report/newReport.jrxml");
            //JasperDesign jasperDesign=JRXmlLoader.load(getClass().getResourceAsStream("/report/newReport.jrxml"));
            System.out.println("file:"+source.getAbsolutePath());
            
            String po_sku=pot+"."+stylet+"."+color_code+"."+size+"."+qty;
                  Map param = new HashMap();
                  param.put("client",client);
                  param.put("total_qty",cum);
                  param.put("COLOR",color);
                  param.put("COL",color_code);
                  param.put("order_qty",order);
                  param.put("sewing_no",no);
                  param.put("codes",code);
                  param.put("posku",po_sku);
                  param.put("issued_qty",plan);
                  System.out.println(listcut(proto_id));
                  ArrayList<cutpart> da=listcut(proto_id);
                  for(int i=0;i<da.size();i++)
                      System.out.println("da:"+da.get(i).getPart());
                  JasperReport jasperReport = JasperCompileManager.compileReport(source.getAbsolutePath());
                  //JRBeanCollectionDataSource beanColDataSource =new JRBeanCollectionDataSource(listdata);
                  JRBeanCollectionDataSource beanCutDataSource =new JRBeanCollectionDataSource(da);
                  //param.put("cutData",beanCutDataSource);
                  //String report=JasperFillManager.fillReportToFile(source.getAbsolutePath(),param,beanColDataSource);
                  JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,param,beanCutDataSource);
                  //JasperViewer.viewReport(jasperPrint);
                  JasperExportManager.exportReportToPdfFile(jasperPrint, "src/report/barcode/"+code+"-"+no+".pdf");
                  
                  Desktop dsk=Desktop.getDesktop();
                  dsk.open(new File("src/report/barcode/"+code+"-"+no+".pdf"));
                  //dsk.
                  //jviewer.setFitPageZoomRatio();
                  /*if(report!=null){
                  JasperExportManager.exportReportToPdfFile(report,
                  "C://users/Padovano/Desktop/sample_report.pdf");
                  }*/
 
                }
 
                catch (Exception e)
                 {
                     e.printStackTrace();
                     System.out.println("Mensaje de Error:"+e.getMessage());
                 }   
        
    }
    
    private ArrayList<cutpart> listcut(int proto_id){
        String requete="select * from cut_parts where proto_id=?";
        System.out.println(proto_id);
        ArrayList<cutpart> cut=new ArrayList<>();
        ResultSet rs = conn.select(requete,proto_id);
        try {
        while (rs.next()){
            cutpart c=new cutpart();
            c.setPart(rs.getString("part"));
            c.setQty(rs.getString("qty"));
            cut.add(c);
        }
    } catch (SQLException ex) {
        Logger.getLogger(sewing.class.getName()).log(Level.SEVERE, null, ex);
    }
        return cut;
    }
}
